import React from 'react'
import Wrapper from './utilities/Wrapper'

const TermsNConditions = () => {
    return (
        <section className='bg-white pt-8 pb-14'>
            <Wrapper>
                <h1 className='font-bold text-3xl sm:text-4xl md:text-6xl mb-5'>Terms and Conditions</h1>
                <p className='text-sm md:text-base'>These terms and conditions are applicable to the use of the website of LIGHT PATH USA LLC, referred to as &ldquo; LIGHT PATH USA,&ldquo; &ldquo;we,&ldquo; &ldquo;our,&ldquo; or &ldquo;us.&ldquo; <br /><br />
                    By accessing or using our website, you agree to abide by these terms and conditions, as well as any other applicable rules, policies, schedules, and terms and conditions or documents published from time to time.
                    The agreement grants you a personal, limited, revocable, non-exclusive, and non-transferable right to use our website and services for personal and non-commercial use within the United States, as permitted under this agreement and the other documents incorporated herein.<br /><br />
                    Our website may contain links to third-party websites. However, we do not control these websites and do not endorse their content. Therefore, your use of third-party links is at your own risk, and we are not responsible for any content, errors, damages, or losses arising from or related to the use or reliance on information from these links.<br /><br />
                    It is crucial to review this agreement carefully before using our website. If you disagree with any part of this agreement, you are not authorized to use our website.<br /><br />
                    The New Jersey Truth-in-Consumer Contract Warranty and Notice Act (&ldquo;TCCWNA&ldquo;) should be reviewed by residents of New Jersey to know their rights.<br /><br />
                    By using our website, you acknowledge and agree to these terms and conditions, as well as any other documents or policies published on our website. If you do not agree with any of these terms, you are not authorized to use our website or services. It is recommended to review these terms periodically to stay up-to-date with any changes or updates.<br /><br />
                    By using this website, you agree to assume all risks associated with the Site Offerings, including the Content, products, and other materials provided by the company. The Content and products provided on the website have not been evaluated by the FDA and are not intended to diagnose, treat, cure or prevent any medical condition or disease. They should not be used as medical advice or substitute for it. It is strongly recommended to consult with a qualified medical professional before using any of the products.<br /><br />
                    The company&lsquo;s products and prescription medications are not intended for individuals under the age of eighteen (18). The information about the company&lsquo;s products and their effectiveness is obtained from reliable third-party sources, such as scientific reports, news agencies, and scientific/research entities. However, the accuracy of this information cannot be guaranteed, and we do not endorse any third-party sources or their methods.<br /><br />
                    All product specifications, performance data, and related information available through the Site Offerings are for informational and illustrative purposes only. They do not guarantee that the products will meet these specifications or performance data, or that they will provide you with any particular benefits or match the results of others who have used them. Your individual results may vary depending on factors such as pre-existing medical conditions, age, weight, body chemistry, diet, and exercise regimen.<br /><br />
                    Using any medication, therapy, or health product from LIGHT PATH USA LLC requires consulting with your healthcare provider or physician beforehand. It is especially important to seek professional medical advice if you have pre-existing medical conditions such as liver, kidney, thyroid disease, high blood pressure, diabetes, skin ailments, anemia, anxiety, depression, or a family history of such physical or mental illnesses. Your physician can then personalize your treatment plan as appropriate and schedule adequate follow-up visits.<br /><br />
                    If you suspect that you are experiencing a medical issue due to the use of any of LIGHT PATH USA LLC&lsquo;s products, prescription medications, or treatments, it is crucial to contact your healthcare provider immediately. It is not recommended to disregard professional medical advice or delay seeking advice due to information obtained from the Site or any other Site offerings.

                </p>
                <p className='text-sm md:text-base font-bold mt-4'>
                    If you are currently undergoing treatment for any illness, taking medication, nursing or pregnant, or have any known allergies to certain components, it is necessary to seek guidance from a healthcare professional or physician before using any of LIGHT PATH USA LLC&lsquo;s products, prescription medications, or therapy for any health condition. To prevent potential allergic reactions, always verify the ingredients of all LIGHT PATH USA LLC products and prescription medications.<br />
                    If you experience any negative health conditions or allergic reactions, it is essential to contact your healthcare provider immediately for the necessary medical assistance.
                </p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>1. Objective</h3>
                <p className='text-sm md:text-base'>This policy governs the use of the Site Offerings provided by LIGHT PATH USA LLC. Users who access or use the Site Offerings agree to be legally bound by this Policy. LIGHT PATH USA LLC reserves the right to modify this Policy without specific notice, except for changes made to the Dispute Resolution Provisions or Billing Provisions. Users should review the latest version of the Policy available on the Site each time they use the Site Offerings. Users who do not agree with any modifications may stop using the Site Offerings. However, by continuing to access or use the Site Offerings, users accept any modifications made to this Policy, except for disputes or charges incurred before changes made in the Dispute Resolution Provisions or Billing Provisions.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>2. Eligibility</h3>
                <p className='text-sm md:text-base'>To use the Site Offerings, users must be 18 years of age or older and located in a jurisdiction where LIGHT PATH USA LLC operates. They must also agree to be legally bound by and comply with the posted Policy, have compatible computing and/or mobile devices, internet access, and necessary software. Users are responsible for any charges or fees incurred by their mobile service or Internet Service Provider related to their use of the Site Offerings. However, meeting these requirements does not guarantee access to the Site Offerings. LIGHT PATH USA LLC reserves the right to terminate users&lsquo; access to the Site Offerings at any time for breaching the Policy, engaging in improper conduct related to the Site Offerings, or performing unauthorized commercial activity by or through the Site Offerings.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>3. Registration</h3>
                <p className='text-sm md:text-base'>Users may need to register to access certain Site Offerings, such as purchasing products or using contact services. To register, users must provide accurate and complete registration information and update it promptly if there are any changes. Failure to do so gives LIGHT PATH USA LLC the right to terminate the use of certain Site Offerings that require registration. LIGHT PATH USA LLC will handle the information provided during the registration process in accordance with its privacy policy.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>4. Purchasing Medication</h3>
                <p className='text-sm md:text-base'>To purchase desired content or medication from LIGHT PATH USA LLC, users need to provide their registration details and complete the relevant form. If the user wishes to buy prescription medication, they must also complete the Telemedicine Services process and obtain approval from a healthcare provider. There are two options for purchasing products on the site: (a) Automatic Renewal Program: This option involves a recurring charge to the user&lsquo;s payment method for the relevant products as long as the automatic renewal program subscription remains active. Users can cancel their subscription up to forty-eight (48) hours before the applicable renewal processing date. (b) One-Time Purchase: This option involves a one-time charge to the user&lsquo;s payment method for the relevant product(s), in addition to shipping and handling charges and any applicable sales tax. If the user&lsquo;s payment method is cancelled or no longer valid, they must inform LIGHT PATH USA LLC immediately to avoid delays or cancellations of the product shipment.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>5. Products</h3>
                <p className='text-sm md:text-base'>LIGHT PATH USA LLC offers a range of products subject to the disclaimers mentioned on the site and contained in the terms and conditions. The prices of the products may change at any time, and LIGHT PATH USA LLC reserves the right to reject any part of an order without prior notice. If any products are no longer available, or if all or part of an order is cancelled, the user will be notified, and LIGHT PATH USA LLC will refund any amount already paid for the ordered products that are no longer available or any cancelled part of the order. All products are subject to availability.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>6.	Refund and Return Policy</h3>
                <p className='text-sm md:text-base'>Users can return LIGHT PATH USA LLC products by contacting a customer care professional at 1-800-250-8494. However, prescription medications are non-returnable and non-refundable.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>7.	Telemedicine Services</h3>
                <p className='text-sm md:text-base'>LIGHT PATH USA LLC provides Telemedicine Services that enable healthcare providers and patients to communicate electronically, regardless of their location. These services may include diagnosis, treatment, follow-up, and patient education. To obtain Prescription Medication, users must complete the medical intake form, which will be submitted to a participating Healthcare Provider. The Healthcare Provider will perform Telemedicine Services to determine whether the user is suitable for Prescription Medication before prescribing it. Please note that LIGHT PATH USA LLC does not provide Telemedicine Services or issue prescriptions for Prescription Medication. Any terms and conditions of such prescriptions will be determined by the Healthcare Provider(s), and LIGHT PATH USA LLC will not be responsible for any medical services and/or medications offered by them. For more information on the risks and benefits of telemedicine, users can refer to the Consent to Telehealth.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>8.	Content</h3>
                <p className='text-sm md:text-base'>The Content available on the site includes product reviews, text, audio, video, photographs, graphics, artwork, testimonials, and other information about LIGHT PATH USA LLC and its products. The Content is compiled, distributed, and displayed by LIGHT PATH USA LLC and third-party providers. LIGHT PATH USA LLC is not responsible for the completeness, accuracy, appropriateness, and/or usefulness of Third-Party Content made available through the Site Offerings. Users should not rely on such Third-Party Content as it may be outdated, harmful, inaccurate, or deceptive. LIGHT PATH USA LLC does not guarantee that the Content and other information posted through the Site Offerings is accurate, complete, up-to-date, or appropriate. By using the Content, users acknowledge that LIGHT PATH USA LLC has no obligation and assumes no liability to them. It is recommended that users exercise caution, use common sense, and prioritize safety when using the Content.</p>

                <p className='text-sm md:text-base mt-7'><span className='text-2xl font-bold'>9.</span> By using the Interactive Services offered by LIGHT PATH USA LLC, you can submit User Content such as feedback. While you retain ownership of the User Content, submitting it to the company grants a worldwide, perpetual, irrevocable, transferrable, royalty-free license for LIGHT PATH USA LLC to use, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit the User Content in any manner, including on third-party sites and services. You must ensure that you have the necessary licenses and permissions for providing the User Content, and that it does not infringe on any third party&lsquo;s intellectual property or proprietary rights or violate any applicable law or regulation. LIGHT PATH USA LLC reserves the right to review, monitor, or remove User Content at any time and for any reason, and may suspend or terminate a user&lsquo;s access and/or account for violating these terms.</p>

                <p className='text-sm md:text-base mt-7'><span className='text-2xl font-bold'>10.</span> When creating an account with LIGHT PATH USA LLC, you may provide personal information that is not considered &ldquo;protected health information&ldquo; or &ldquo;medical information.&ldquo; However, if you request Prescription Medications or certain LIGHT PATH USA LLC Products, you may provide health or medical information that may be protected under applicable laws like HIPAA. Although LIGHT PATH USA LLC is not classified as a &ldquo;covered entity&ldquo; under HIPAA, it may act as a &ldquo;business associate&ldquo; of Healthcare Providers and be subject to certain provisions of HIPAA regarding &ldquo;protected health information&ldquo; that you provide to the Healthcare Providers. Any medical or health information subject to specific protections under applicable state laws will comply with such laws. Information that has been de-identified in accordance with applicable laws is not considered Protected Information.</p>


                <p className='text-sm md:text-base mt-7'><span className='text-2xl font-bold'>11.</span> By accessing and using the Site Offerings, you affirm and guarantee that all information provided is truthful, accurate, up-to-date, and comprehensive. You also agree to maintain and update this information as required. Additionally, you acknowledge that the Products are for individual use only and are not intended for resale. You understand that the Agreement is legally binding, and that its execution, delivery, and performance will not conflict with any applicable laws or agreements.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>12. Indemnification</h3>
                <p className='text-sm md:text-base'>By using the Site Offerings, you agree to indemnify, defend, and hold harmless LIGHT PATH USA LLC, its shareholders, directors, officers, employees, and agents from any claims, damages, debts, demands, or liabilities arising from your violation of this Agreement or your misuse of the Site Offerings. This includes any data or work transmitted or received by you, disputes with Healthcare Providers and/or third parties, and any improper or unauthorized use of the Site Offerings. LIGHT PATH USA LLC, its parent, subsidiaries, and affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers, and attorneys, may enforce these provisions against you directly.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>13. Proprietary Rights</h3>
                <p className='text-sm md:text-base'>The Site Offerings and all proprietary content, including information, graphics, design, compilation, software, documentation, marks, business processes, and service names, are the exclusive property of LIGHT PATH USA LLC. Unauthorized use of any trademark is strictly prohibited without express written consent from LIGHT PATH USA LLC. You may not create derivative works or distribute, copy, recompile, disassemble, or reverse engineer the proprietary content without prior written consent. All proprietary content is protected by United States and foreign laws.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>14. Legal Warning</h3>
                <p className='text-sm md:text-base'>You must exercise caution and good judgment when accessing and using the Site Offerings and refrain from interfering with the Site Offerings&lsquo; operations. This includes vandalism, tampering, damaging, or destroying the Site Offerings in any way. Any such attempts will violate criminal and civil laws, and LIGHT PATH USA LLC will pursue legal remedies against the offending party or entity to the fullest extent allowed by law and equity.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>15. Disclaimer of Warranties</h3>
                <p className='text-sm md:text-base'>The Site Offerings and related products and services are provided &ldquo;as is&ldquo; and subject to their availability. Users access and use the Site Offerings at their own risk and discretion. Neither LIGHT PATH USA LLC nor any third-party service providers make any express or implied representations or warranties regarding this agreement, the Site Offerings, or the products and services available through them. This includes any warranties of merchantability, title, or fitness for a particular purpose. Using the Site Offerings does not guarantee any medical benefits or other health-related outcomes. Additionally, LIGHT PATH USA LLC does not warrant that the Site Offerings and related products and services will be error-free, uninterrupted, or free from defects, delays, cyber attacks, malware, or other adverse incidents. Any advice or information obtained from LIGHT PATH USA LLC or the Site Offerings, whether oral or written, does not create any warranty not expressly stated in this Agreement. Users should exercise their own judgment and discretion when using the Site Offerings.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>16. Limitation of Liability </h3>
                <p className='text-sm md:text-base'>The use of the Site Offerings or any products and services available through them is at the User&lsquo;s own risk, and LIGHT PATH USA LLC cannot be held liable for any damages, direct or indirect, incidental, special, consequential, or exemplary, arising from such use. Users acknowledge that this includes loss of profits, goodwill, data, or any other intangible losses. Users agree that this limitation of liability applies to all causes of action, including breach of contract, breach of warranty, negligence, strict liability, misrepresentation, and any and all other torts. LIGHT PATH USA LLC is not liable for any obligations, liabilities, or claims that exceed the limitations specified in this section. If any loss, cost, damage, liability, or expense is incurred, the total liability of LIGHT PATH USA LLC to any User shall not exceed five hundred dollars ($500.00) or the amount paid by the User, if any, for the right to access or participate in any activity related to the Site Offerings, whichever is lesser. Users must bring any claims arising from the use of the Site Offerings or any products and services offered by LIGHT PATH USA LLC or third-party providers within one (1) year of the event that led to the cause of action. The negation of damages is a fundamental element of the basis of the agreement between each User and LIGHT PATH USA LLC. Without such limitations, access to the Site Offerings would not be provided to Users. Users must understand and agree that this limitation of liability applies to all Site Offerings and products and services offered by LIGHT PATH USA LLC, as well as any third-party offering products or services through the service. Note that limitations on liability may not be permitted in some jurisdictions, and in such cases, LIGHT PATH USA LLC&lsquo;s liability shall be limited to the maximum extent permitted by law.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>17. Copyright Policy and DMCA Compliance </h3>
                <p className='text-sm md:text-base'>At LIGHT PATH USA LLC, we are committed to upholding copyright law and complying with the Digital Millennium Copyright Act (DMCA). We take seriously any allegations of copyright infringement and will respond promptly by removing infringing content or terminating user accounts as necessary. If you suspect that copyrighted material is available on our Site without proper authorization, you may submit a notification to our Designated Agent. In order for us to investigate your claim of copyright infringement under 17 U.S.C. § 512(c), your notification must include the following information:</p>

                <ul className='mt-4 space-y-3'>
                    <li>(a) The signature of an authorized person acting on behalf of the copyright owner;</li>
                    <li> (b) Identification and location of the copyrighted work you claim has been infringed;</li>
                    <li> (c) A statement from you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</li>
                    <li> (d) Your contact information, such as a telephone number or email address; and</li>
                    <li> (e) A statement by you that the information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner&lsquo;s behalf.
                        Upon receipt of your notification, we will take appropriate actions. To submit a notice of claim or for more information, please contact us.</li>
                </ul>

                <h3 className='text-2xl font-bold mt-7 mb-3'>18. Modification of Content </h3>
                <p className='text-sm md:text-base'>LIGHT PATH USA LLC retains the right to modify, edit, or delete any material, documents, or information that appears on the Site at its discretion.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>19. Use of User Data </h3>
                <p className='text-sm md:text-base'>All user-generated data submitted through the Site Offerings, including Registration Data, will be subject to the Privacy Policy.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>20. Governing Law </h3>
                <p className='text-sm md:text-base'>The Agreement shall be governed and interpreted by the laws of the State of New York, regardless of any conflict of law principles. All parties agree that the Agreement shall be deemed to have been executed and performed in New York, NY.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>21. Dispute Resolution and Arbitration </h3>
                <p className='text-sm md:text-base'>The parties to this Agreement agree to resolve any disputes through arbitration. If there is a dispute regarding the Site Offerings or a party&lsquo;s violation of the Agreement, the parties must refer the dispute to the American Arbitration Association (&ldquo;AAA&ldquo;) in New York, NY, following the current Commercial Arbitration rules of the AAA. The parties must attempt to negotiate in good faith to resolve the issue or dispute. If the parties fail to reach a satisfactory resolution, the party initiating the dispute must submit a written description of the dispute, along with all relevant documents and information, and the proposed resolution to LIGHT PATH USA LLC, Attention: Customer Service Department - 201 Sigma Drive Suite 300, Summerville, SC, 29486.</p>

                <p className='mt-4 text-sm md:text-base'>If the amount in dispute is less than Ten Thousand Dollars ($10,000.00), the arbitration may proceed in person, by telephone, or based on submissions. If the arbitrator awards relief greater than the final settlement offer, all filing, administration, and arbitrator fees associated with the arbitration will be paid by the parties. If an attorney is retained for the arbitration, LIGHT PATH USA LLC will reimburse reasonable attorneys&lsquo; fees. The award will be final and binding, and a judgment may be entered in any court of competent jurisdiction. <br /><br />
                    You agree not to initiate, join, or participate in any class action lawsuit against LIGHT PATH USA LLC, their respective employees, officers, directors, members, representatives, or assigns, to the extent permitted by law. This provision does not waive any of your rights or remedies to pursue a claim individually in binding arbitration. Injunctive relief may be sought to prevent such a lawsuit or remove you as a participant, and you agree to pay the attorney&lsquo;s fees and court costs incurred by any Covered Party.<br /><br />
                    You may opt-out of these dispute resolution provisions by providing written notice of your decision within thirty (30) days of your first access to the Site. However, any disputes arising before or after the thirty-day period will be subject to these dispute resolution provisions.
                </p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>22. California Consumer Rights</h3>
                <p className='text-sm md:text-base'>If you are a California resident, you have the right to file a complaint with the California Department of Consumer Affairs. You may do so by phone at 916-445-1254 or 800-952-5210, or by email to dca@dca.ca.gov. Your complaints will be subject to the provisions of Cal. Civ. Code Sec. 1789.3.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>23. Proposition 65 Warnings</h3>
                <p className='text-sm md:text-base'>To comply with California law Proposition 65, products containing chemicals known to cause cancer or reproductive toxicity must carry warnings to protect California consumers. Over 850 chemicals are listed on the California Office of Environmental Health Hazard Assessment. Products associated with this page may contain Bisphenol A (BPA), which can harm the female reproductive system. Warnings for jar lids and bottle caps that may also contain BPA are included. More information is available on www.P65Warnings.ca.gov/BPA. To learn more about Proposition 65 and its regulations, visit https://oehha.ca.gov/proposition-65/law/proposition-65-law-and-regulations. Details of new warning requirements can be found on https://www.p65warnings.ca.gov/new-proposition-65-warnings.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>24. Precedence</h3>
                <p className='text-sm md:text-base'>If there is a conflict or inconsistency between the Site Offerings and the Agreement, the Agreement shall take precedence. LIGHT PATH USA LLC&lsquo;s failure to enforce any provision of the Agreement shall not be construed as a waiver of that provision or the right to enforce it.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>25. No Agency Relationship</h3>
                <p className='text-sm md:text-base'>This Agreement does not establish an agency, joint venture, or partnership relationship between the user and LIGHT PATH USA LLC. Neither party is authorized to act as an agent or bind the other party.</p>

                <h3 className='text-2xl font-bold mt-7 mb-3'>26. Assignment</h3>
                <p className='text-sm md:text-base'>LIGHT PATH USA LLC may assign, transfer, or delegate its rights and obligations under the Agreement to any third party, in whole or in part, without prior notice to the user. However, the user may not assign or transfer the Agreement or delegate their responsibilities under it without LIGHT PATH USA LLC&lsquo;s prior written consent.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>27. Severability</h3>
                <p className='text-sm md:text-base'>If any provision of this Agreement is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions of this Agreement will remain in full force and effect. The parties will attempt to modify the unenforceable provision to make it enforceable, or if modification is not possible, the provision will be deemed eliminated from this Agreement.</p>


                <h3 className='text-2xl font-bold mt-7 mb-3'>28. Contact Us</h3>
                <p className='text-sm md:text-base'>If you have any questions, concerns, or feedback about this Agreement or the Site Offerings, you can contact us using the information provided on the &ldquo;Contact Us&ldquo; page of the Site. You may also email us at info@lightpathrx.com, call 1-800-250-8494, or send mail to LIGHT PATH USA LLC (d/b/a LIGHT PATH USA LLC), 201 Sigma Drive Suite 300, Summerville, SC, 29486. We will make our best efforts to respond to your inquiry in a timely and appropriate manner.</p>
            </Wrapper>
        </section>
    )
}

export default TermsNConditions