import Head from 'next/head'
import User from '../../components/User/Index'

export default function UserPage() {
    return (
        <>
            <Head>
                <title>Account | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <User />
        </>
    )
}
