import Head from 'next/head'
import Checkout from '../../components/Checkout/Index'

export default function Home() {
  return (
    <>
      <Head>
        <title>Checkout | LightPathRX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout />
    </>
  )
}
