import Head from 'next/head'
import ConsentToTelehealth from '../../components/ConsentToTelehealth'

export default function ConsentToTelehealthPage() {
    return (
        <>
            <Head>
                <title>Consent to Telehealth | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ConsentToTelehealth />
        </>
    )
}
