import Head from 'next/head'
import ContactUs from '../../components/ContactUs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Contact us | LightPathRX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactUs />
    </>
  )
}
