import Head from 'next/head'
import ErectileFunction from '../../components/Products/ErectileFunction/Index'

export default function ErcetileFunctionPage() {
    return (
        <>
            <Head>
                <title>Erectile Function | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ErectileFunction />
        </>
    )
}
