import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>How it works | LightPathRX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>How it works content</p>
    </>
  )
}
