import Head from 'next/head'
import PrivacyPolicy from '../../components/PrivacyPolicy'

export default function PrivacyPolicyPage() {
    return (
        <>
            <Head>
                <title>Privacy Policy | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PrivacyPolicy />
        </>
    )
}
