import Head from 'next/head'
import Tadalafil from '../../components/Products/Tadalafil/Index'

export default function Home() {
    return (
        <>
            <Head>
                <title>Tadalafil | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Tadalafil />
        </>
    )
}
