import Head from 'next/head'
import TermsNConditions from '../../components/TermsNConditions'

export default function TermnConditionPage() {
    return (
        <>
            <Head>
                <title>Terms and Conditions | LightPathRX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TermsNConditions />
        </>
    )
}
